# Generated by Django 6.0.2 on 2026-02-09 21:51

import common.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(default=common.models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('workout_frequency', models.IntegerField(default=0)),
                ('member_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_workouts', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('working_out', 'Working Out'), ('deactivated', 'Deactivated')], default='offline', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
