# Generated by Django 6.0.2 on 2026-02-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_friend_requests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='distance_unit',
            field=models.CharField(choices=[('miles', 'Miles'), ('km', 'Kilometers')], default='miles', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_friend_requests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_friend_workouts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_group_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_leaderboard_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_reactions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_workout_invites',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_workout_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_zaps',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public - Anyone can view'), ('friends', 'Friends Only'), ('private', 'Only Me')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_online_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_personal_records',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_streak',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_workout_goal',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_unit',
            field=models.CharField(choices=[('lbs', 'Pounds (lbs)'), ('kg', 'Kilograms (kg)')], default='lbs', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='workout_post_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Only Me')], default='friends', max_length=10),
        ),
    ]
