# Generated by Django 6.0.2 on 2026-02-17 02:45

from django.db import migrations, models


def copy_enrolled_gym_to_m2m(apps, schema_editor):
    """Copy existing enrolled_gym FK values into the new enrolled_gyms M2M."""
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(enrolled_gym__isnull=False):
        user.enrolled_gyms.add(user.enrolled_gym)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_allow_friend_requests_user_distance_unit_and_more"),
        ("gyms", "0004_workoutinvite_invited_user"),
    ]

    operations = [
        # 1. Add the new M2M field
        migrations.AddField(
            model_name="user",
            name="enrolled_gyms",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_users", to="gyms.gym"
            ),
        ),
        # 2. Copy existing FK data into M2M
        migrations.RunPython(copy_enrolled_gym_to_m2m, migrations.RunPython.noop),
        # 3. Remove the old FK field
        migrations.RemoveField(
            model_name="user",
            name="enrolled_gym",
        ),
    ]
