# Generated by Django 6.0.2 on 2026-03-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checkin_visible_following',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='checkin_visible_friends',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='checkin_visible_gyms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='checkin_visible_orgs',
            field=models.BooleanField(default=True),
        ),
    ]
