# Generated by Django 6.0.2 on 2026-02-09 21:51

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=common.models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('like_post', 'Like Post'), ('comment', 'Comment'), ('follow', 'Follow'), ('pr', 'Personal Record'), ('group_invite', 'Group Invite'), ('workout_invite', 'Workout Invite'), ('join_request', 'Join Request')], max_length=20)),
                ('target_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('workout', 'Workout'), ('quick_workout', 'Quick Workout'), ('personal_record', 'Personal Record'), ('group', 'Group'), ('user', 'User'), ('workout_invite', 'Workout Invite')], max_length=20)),
                ('target_id', models.CharField(max_length=36)),
                ('context_type', models.CharField(blank=True, max_length=20)),
                ('context_id', models.CharField(blank=True, max_length=36)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='idx_notif_recipient'), models.Index(fields=['recipient', 'read_at'], name='idx_notif_unread')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('context_id', ''), ('context_type', '')), models.Q(models.Q(('context_type', ''), _negated=True), models.Q(('context_id', ''), _negated=True)), _connector='OR'), name='notif_context_all_or_nothing')],
            },
        ),
    ]
