# Generated by Django 6.0.2 on 2026-02-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("like_post", "Like Post"),
                    ("comment", "Comment"),
                    ("follow", "Follow"),
                    ("pr", "Personal Record"),
                    ("workout_invite", "Workout Invite"),
                    ("join_request", "Join Request"),
                ],
                max_length=20,
            ),
        ),
    ]
