# Generated by Django 6.0.2 on 2026-03-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_add_like_checkin_like_comment_mention"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("like_post", "Like Post"),
                    ("like_checkin", "Like Checkin"),
                    ("like_comment", "Like Comment"),
                    ("comment", "Comment"),
                    ("follow", "Follow"),
                    ("pr", "Personal Record"),
                    ("mention", "Mention"),
                    ("workout_invite", "Workout Invite"),
                    ("join_request", "Join Request"),
                    ("join_accepted", "Join Accepted"),
                ],
                max_length=20,
            ),
        ),
    ]
