# Generated by Django 6.0.1 on 2026-02-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupmember",
            options={"ordering": ["-role", "-joined_at"]},
        ),
    ]
