# Generated by Django 6.0.1 on 2026-02-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupmember",
            options={"ordering": []},
        ),
        migrations.RemoveField(
            model_name="group",
            name="avatar",
        ),
        migrations.AddField(
            model_name="group",
            name="privacy",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("creator", "Creator"),
                    ("admin", "Admin"),
                    ("member", "Member"),
                ],
                default="member",
                max_length=10,
            ),
        ),
    ]
