# Generated by Django 6.0.2 on 2026-02-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_group_avatar_groupinvitecode_groupjoinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="last_streak_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="longest_group_streak",
            field=models.IntegerField(default=0),
        ),
    ]
