# Generated by Django 6.0.2 on 2026-02-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_group_last_streak_date_group_longest_group_streak"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="last_checkin_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
