# Generated by Django 6.0.2 on 2026-02-24 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="announcementreaction",
            name="idx_ann_reaction_announcement",
        ),
    ]
