# Generated by Django 6.0.2 on 2026-02-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_drop_duplicate_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgmember",
            name="last_announcements_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
