# Generated by Django 6.0.2 on 2026-03-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_challenges_raffles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgchallenge",
            name="announcement",
        ),
        migrations.RemoveConstraint(
            model_name="orgchallengecompletion",
            name="unique_challenge_completion",
        ),
        migrations.RemoveField(
            model_name="orgraffle",
            name="announcement",
        ),
        migrations.RemoveField(
            model_name="orgraffle",
            name="winner",
        ),
        migrations.RemoveConstraint(
            model_name="orgraffleentry",
            name="unique_raffle_entry_per_day",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="kind",
        ),
        migrations.RemoveField(
            model_name="orgchallengecompletion",
            name="challenge",
        ),
        migrations.RemoveField(
            model_name="orgchallengecompletion",
            name="user",
        ),
        migrations.RemoveField(
            model_name="orgraffleentry",
            name="raffle",
        ),
        migrations.RemoveField(
            model_name="orgraffleentry",
            name="user",
        ),
        migrations.DeleteModel(
            name="OrgChallenge",
        ),
        migrations.DeleteModel(
            name="OrgChallengeCompletion",
        ),
        migrations.DeleteModel(
            name="OrgRaffle",
        ),
        migrations.DeleteModel(
            name="OrgRaffleEntry",
        ),
    ]
