# Generated by Django 6.0.1 on 2026-02-04 04:40

import common.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.models.generate_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("display_name", models.CharField(max_length=50)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("avatar", models.CharField(blank=True, max_length=255, null=True)),
                ("bio", models.TextField(blank=True)),
                ("workout_frequency", models.IntegerField(default=0)),
                (
                    "member_since",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("total_workouts", models.IntegerField(default=0)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("current_activity", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["username"],
            },
        ),
    ]
