# Generated by Django 6.0.1 on 2026-02-04 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("gyms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_gym",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_users",
                to="gyms.gym",
            ),
        ),
    ]
