# Generated by Django 6.0.1 on 2026-02-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workout",
            name="unique_workout_per_user_per_day",
        ),
    ]
