# Generated by Django 6.0.2 on 2026-02-10 04:40

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseCatalog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.models.generate_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("chest", "Chest"),
                            ("back", "Back"),
                            ("shoulders", "Shoulders"),
                            ("arms", "Arms"),
                            ("legs", "Legs"),
                            ("core", "Core"),
                            ("cardio", "Cardio"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("default_sets", models.PositiveIntegerField(default=3)),
                ("default_reps", models.PositiveIntegerField(default=10)),
                (
                    "default_weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("is_cardio", models.BooleanField(default=False)),
                ("is_bodyweight", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Exercise Catalog",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseSet",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.models.generate_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("set_number", models.PositiveIntegerField()),
                ("reps", models.PositiveIntegerField(default=0)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_sets",
                        to="workouts.exercise",
                    ),
                ),
            ],
            options={
                "ordering": ["set_number"],
                "unique_together": {("exercise", "set_number")},
            },
        ),
    ]
