# Generated by Django 6.0.2 on 2026-02-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalrecord',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='pr_videos/'),
        ),
    ]
