# Generated by Django 6.0.2 on 2026-02-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_exercisecatalog_exerciseset"),
        ("workouts", "0002_personalrecord_video"),
    ]

    operations = []
