# Generated by Django 6.0.2 on 2026-02-17 08:00

from django.db import migrations


def copy_last_workout_to_streak_date(apps, schema_editor):
    Streak = apps.get_model('workouts', 'Streak')
    for streak in Streak.objects.filter(last_workout_date__isnull=False, last_streak_date__isnull=True):
        streak.last_streak_date = streak.last_workout_date
        streak.last_activity_type = 'workout'
        streak.save(update_fields=['last_streak_date', 'last_activity_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_streak_last_activity_type_streak_last_streak_date_and_more'),
    ]

    operations = [
        migrations.RunPython(
            copy_last_workout_to_streak_date,
            migrations.RunPython.noop,
        ),
    ]
