# Generated by Django 6.0.2 on 2026-03-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_achievement_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisecatalog',
            name='muscle_group',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
