# Generated by Django 6.0.2 on 2026-03-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_add_muscle_group_to_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisecatalog',
            name='category',
            field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('arms', 'Arms'), ('legs', 'Legs'), ('core', 'Core'), ('cardio', 'Cardio'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
