# Generated by Django 6.0.2 on 2026-03-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0009_alter_exercisecatalog_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisecatalog",
            name="category",
            field=models.CharField(
                choices=[
                    ("chest", "Chest"),
                    ("back", "Back"),
                    ("shoulders", "Shoulders"),
                    ("biceps", "Biceps"),
                    ("triceps", "Triceps"),
                    ("legs", "Legs"),
                    ("core", "Core"),
                    ("cardio", "Cardio"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
