# Generated by Django 6.0.1 on 2026-02-07 03:04

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.models.generate_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("storage_key", models.CharField(max_length=255)),
                ("thumbnail_key", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("byte_size", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=15,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.models.generate_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination_type",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("user", "User"),
                            ("group", "Group"),
                            ("personal_record", "Personal Record"),
                            ("message", "Message"),
                            ("quick_workout", "Quick Workout"),
                        ],
                        max_length=20,
                    ),
                ),
                ("destination_id", models.CharField(max_length=36)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("avatar", "Avatar"),
                            ("cover", "Cover"),
                            ("inline", "Inline"),
                        ],
                        max_length=10,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="media.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_media_asset_user"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(fields=["status"], name="idx_media_asset_status"),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.UniqueConstraint(
                fields=("storage_key",), name="unique_storage_key"
            ),
        ),
        migrations.AddIndex(
            model_name="medialink",
            index=models.Index(
                fields=["destination_type", "destination_id"],
                name="idx_media_link_dest",
            ),
        ),
        migrations.AddIndex(
            model_name="medialink",
            index=models.Index(fields=["asset"], name="idx_media_link_asset"),
        ),
        migrations.AddConstraint(
            model_name="medialink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type__in", ["avatar", "cover"])),
                fields=("destination_type", "destination_id", "type"),
                name="unique_avatar_or_cover_per_destination",
            ),
        ),
        migrations.AddConstraint(
            model_name="medialink",
            constraint=models.UniqueConstraint(
                fields=("asset", "destination_type", "destination_id", "type"),
                name="unique_media_link",
            ),
        ),
    ]
