# Generated by Django 6.0.2 on 2026-02-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_drop_duplicate_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medialink",
            name="destination_type",
            field=models.CharField(
                choices=[
                    ("post", "Post"),
                    ("user", "User"),
                    ("group", "Group"),
                    ("personal_record", "Personal Record"),
                    ("message", "Message"),
                    ("quick_workout", "Quick Workout"),
                    ("announcement", "Announcement"),
                ],
                max_length=20,
            ),
        ),
    ]
