# Generated by Django 6.0.2 on 2026-03-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_medialink_destination_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medialink',
            name='type',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('cover', 'Cover'), ('inline', 'Inline'), ('front_camera', 'Front Camera')], max_length=15),
        ),
    ]
