import { FeedItem, Comment } from '../types/feed';

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();

export const SAMPLE_FEED: FeedItem[] = [
  {
    id: 1,
    type: 'post',
    user: {
      id: 1,
      username: 'alexfit',
      display_name: 'Alex Johnson',
      avatar_url: null,
      streak: 14,
    },
    created_at: hoursAgo(1),
    description:
      'Just finished a killer push session. Hit a new bench PR today! The grind never stops.',
    location_name: 'Iron Paradise Gym',
    photo_url: null,
    link_url: null,
    like_count: 24,
    comment_count: 5,
    user_liked: false,
    workout: {
      id: 1,
      exercise_count: 5,
      total_sets: 18,
      duration_minutes: 72,
      exercises: [
        { name: 'Bench Press', sets: 4 },
        { name: 'Incline Dumbbell Press', sets: 4 },
        { name: 'Cable Flyes', sets: 3 },
        { name: 'Tricep Pushdowns', sets: 4 },
        { name: 'Overhead Tricep Extension', sets: 3 },
      ],
    },
    personal_record: {
      id: 1,
      exercise_name: 'Bench Press',
      value: 225,
      unit: 'lbs',
    },
    poll: null,
    visibility: 'main',
  },
  {
    id: 2,
    type: 'checkin',
    user: {
      id: 2,
      username: 'sarahlifts',
      display_name: 'Sarah Chen',
      avatar_url: null,
      streak: 30,
    },
    created_at: hoursAgo(3),
    description:
      'Morning cardio hits different. 5K in 22 minutes - getting faster every week!',
    location_name: 'Central Park',
    photo_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800',
    link_url: null,
    like_count: 18,
    comment_count: 3,
    user_liked: true,
    workout: null,
    personal_record: null,
    poll: null,
    workout_type: 'Cardio',
    visibility: 'main',
  },
  {
    id: 3,
    type: 'post',
    user: {
      id: 3,
      username: 'mikegains',
      display_name: 'Mike Thompson',
      avatar_url: null,
      streak: 7,
    },
    created_at: hoursAgo(5),
    description: 'What split are you running this month?',
    location_name: null,
    photo_url: null,
    link_url: null,
    like_count: 8,
    comment_count: 12,
    user_liked: false,
    workout: null,
    personal_record: null,
    poll: {
      id: 1,
      question: "What's your current training split?",
      options: [
        { id: 1, text: 'Push/Pull/Legs', votes: 45, order: 0 },
        { id: 2, text: 'Upper/Lower', votes: 20, order: 1 },
        { id: 3, text: 'Bro Split', votes: 15, order: 2 },
        { id: 4, text: 'Full Body', votes: 12, order: 3 },
      ],
      total_votes: 92,
      user_vote_id: null,
      is_active: true,
      ends_at: new Date(now.getTime() + 86400000).toISOString(),
    },
    visibility: 'main',
  },
  {
    id: 4,
    type: 'post',
    user: {
      id: 4,
      username: 'fitjess',
      display_name: 'Jessica Park',
      avatar_url: null,
      streak: 21,
    },
    created_at: hoursAgo(8),
    description:
      'Leg day complete. These Bulgarian split squats are no joke. Check out this form guide that helped me a lot!',
    location_name: 'FitZone',
    photo_url: null,
    link_url: 'https://www.strongerbyscience.com/bulgarian-split-squat/',
    like_count: 31,
    comment_count: 7,
    user_liked: false,
    workout: {
      id: 2,
      exercise_count: 6,
      total_sets: 22,
      duration_minutes: 65,
      exercises: [
        { name: 'Barbell Squats', sets: 5 },
        { name: 'Bulgarian Split Squats', sets: 4 },
        { name: 'Leg Press', sets: 4 },
        { name: 'Romanian Deadlifts', sets: 4 },
        { name: 'Leg Curls', sets: 3 },
        { name: 'Calf Raises', sets: 4 },
      ],
    },
    personal_record: null,
    poll: null,
    visibility: 'main',
  },
  {
    id: 5,
    type: 'checkin',
    user: {
      id: 5,
      username: 'danielstrong',
      display_name: 'Daniel Kim',
      avatar_url: null,
    },
    created_at: hoursAgo(12),
    description: 'Back and biceps. Simple and effective.',
    location_name: 'Gold\'s Gym',
    photo_url: null,
    link_url: null,
    like_count: 6,
    comment_count: 1,
    user_liked: false,
    workout: null,
    personal_record: null,
    poll: null,
    workout_type: 'Strength',
    visibility: 'friends',
  },
];

export const SAMPLE_COMMENTS: Comment[] = [
  {
    id: 1,
    user: {
      id: 2,
      username: 'sarahlifts',
      display_name: 'Sarah Chen',
      avatar_url: null,
    },
    description: 'Amazing PR! 225 is a huge milestone. Keep crushing it!',
    created_at: hoursAgo(0.5),
    like_count: 3,
    user_liked: false,
    reply_count: 2,
    replies: [
      {
        id: 10,
        user: {
          id: 1,
          username: 'alexfit',
          display_name: 'Alex Johnson',
          avatar_url: null,
        },
        description: 'Thanks Sarah! Next goal is 250!',
        created_at: hoursAgo(0.3),
        like_count: 1,
        user_liked: false,
        reply_count: 0,
      },
      {
        id: 11,
        user: {
          id: 3,
          username: 'mikegains',
          display_name: 'Mike Thompson',
          avatar_url: null,
        },
        description: "You'll get there in no time!",
        created_at: hoursAgo(0.2),
        like_count: 0,
        user_liked: false,
        reply_count: 0,
      },
    ],
  },
  {
    id: 2,
    user: {
      id: 3,
      username: 'mikegains',
      display_name: 'Mike Thompson',
      avatar_url: null,
    },
    description: 'Solid workout. How long did the bench PR take you to hit?',
    created_at: hoursAgo(0.8),
    like_count: 1,
    user_liked: true,
    reply_count: 0,
  },
  {
    id: 3,
    user: {
      id: 4,
      username: 'fitjess',
      display_name: 'Jessica Park',
      avatar_url: null,
    },
    description: 'Insane progress! What program are you following?',
    created_at: hoursAgo(1),
    like_count: 0,
    user_liked: false,
    reply_count: 0,
  },
];
