# Generated by Django 6.0.2 on 2026-02-09 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
        ('social', '0001_initial'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='streak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='workouts.streak'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='workouts.workout'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.post'),
        ),
        migrations.AddField(
            model_name='quickworkout',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_workouts', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='quickworkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='quick_workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.quickworkout'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.comment'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.post'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='quick_workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.quickworkout'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block'),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='no_self_block'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='unique_follow'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='no_self_follow'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['gym', 'rank'], name='idx_leaderboard_gym_rank'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.UniqueConstraint(fields=('user', 'gym'), name='unique_leaderboard_entry_per_gym'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at'], name='idx_post_user'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['visibility', '-created_at'], name='idx_post_visibility'),
        ),
        migrations.AddIndex(
            model_name='quickworkout',
            index=models.Index(fields=['user', '-created_at'], name='idx_quick_workout_user'),
        ),
        migrations.AddIndex(
            model_name='quickworkout',
            index=models.Index(fields=['visibility', '-created_at'], name='idx_quick_workout_visibility'),
        ),
        migrations.AddConstraint(
            model_name='quickworkout',
            constraint=models.CheckConstraint(condition=models.Q(('location__isnull', False), models.Q(('location_name', ''), _negated=True), _connector='OR'), name='quick_workout_requires_location'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='idx_comment_post'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['quick_workout', 'created_at'], name='idx_comment_quick_workout'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'created_at'], name='idx_comment_user'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('post__isnull', False), ('quick_workout__isnull', True)), models.Q(('post__isnull', True), ('quick_workout__isnull', False)), _connector='OR'), name='comment_on_post_or_quick_workout'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['post', 'created_at'], name='idx_reaction_post'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['quick_workout', 'created_at'], name='idx_reaction_quick_workout'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['comment', 'created_at'], name='idx_reaction_comment'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['user', 'created_at'], name='idx_reaction_user'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('post__isnull', False), ('quick_workout__isnull', True)), models.Q(('comment__isnull', True), ('post__isnull', True), ('quick_workout__isnull', False)), models.Q(('comment__isnull', False), ('post__isnull', True), ('quick_workout__isnull', True)), _connector='OR'), name='reaction_on_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('post', 'user'), name='unique_reaction_per_user_per_post'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('quick_workout__isnull', False)), fields=('quick_workout', 'user'), name='unique_reaction_per_user_per_quick_workout'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('comment', 'user'), name='unique_reaction_per_user_per_comment'),
        ),
    ]
