# Generated by Django 6.0.2 on 2026-02-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
