# Generated by Django 6.0.2 on 2026-02-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_remove_comment_comment_on_post_or_quick_workout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="title",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
