# Generated by Django 6.0.2 on 2026-02-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0006_add_poll_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="title",
        ),
    ]
