# Generated by Django 6.0.2 on 2026-02-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0007_remove_poll_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="posts/videos/"),
        ),
    ]
