# Generated by Django 6.0.2 on 2026-02-24 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_add_video_to_post'),
        ('workouts', '0006_drop_duplicate_constraint'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quickworkout',
            name='idx_quick_workout_visibility',
        ),
        migrations.AddField(
            model_name='quickworkout',
            name='audience',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='quickworkout',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='workouts.workout'),
        ),
        migrations.RemoveField(
            model_name='quickworkout',
            name='visibility',
        ),
    ]
