# Generated by Django 6.0.2 on 2026-03-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0014_post_video_dimensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickworkout",
            name="is_front_camera",
            field=models.BooleanField(default=False),
        ),
    ]
