# Generated by Django 6.0.2 on 2026-03-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_postmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostMedia',
        ),
    ]
