# Generated by Django 6.0.1 on 2026-02-07 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("messaging", "0001_initial"),
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_messages",
                to="social.post",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="messageread",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_receipts",
                to="messaging.message",
            ),
        ),
        migrations.AddField(
            model_name="messageread",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_receipts",
                to="accounts.user",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["recipient", "-created_at"], name="idx_message_recipient"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["group", "-created_at"], name="idx_message_group"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "-created_at"], name="idx_message_sender"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("group__isnull", True), ("recipient__isnull", False)),
                    models.Q(("group__isnull", False), ("recipient__isnull", True)),
                    _connector="OR",
                ),
                name="message_recipient_or_group",
            ),
        ),
        migrations.AddIndex(
            model_name="messageread",
            index=models.Index(
                fields=["user", "-read_at"], name="idx_read_receipt_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="messageread",
            constraint=models.UniqueConstraint(
                fields=("message", "user"), name="unique_read_receipt"
            ),
        ),
    ]
