# Generated by Django 6.0.2 on 2026-02-17 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_initial"),
        ("social", "0008_add_video_to_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="quick_workout",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_messages",
                to="social.quickworkout",
            ),
        ),
    ]
