# Generated by Django 6.0.2 on 2026-02-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_add_quick_workout_to_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
    ]
