# Generated by Django 6.0.2 on 2026-03-07 08:25

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_messageread_user_message_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxentry',
            name='id',
            field=models.CharField(default=common.models.generate_uuid, max_length=36, primary_key=True, serialize=False),
        ),
    ]
