# Generated by Django 6.0.2 on 2026-02-24 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0011_alter_inboxentry_id_alter_message_content_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="messagereaction",
            name="idx_message_reaction_message",
        ),
    ]
