# Generated by Django 6.0.2 on 2026-03-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0012_drop_duplicate_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxentry",
            name="latest_reaction_actor",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="inboxentry",
            name="latest_reaction_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inboxentry",
            name="latest_reaction_message_sender_id",
            field=models.CharField(blank=True, default="", max_length=36),
        ),
    ]
