# Generated by Django 6.0.1 on 2026-02-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="google_place_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="gym",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="gym",
            name="rating_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gym",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="gym",
            name="amenities",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="gym",
            name="hours",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="gym",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gym",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gym",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
