# Generated by Django 6.0.2 on 2026-02-18 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_group_last_streak_date_group_longest_group_streak"),
        ("gyms", "0004_workoutinvite_invited_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutinvite",
            name="total_spots",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="workoutinvite",
            name="workout_chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workout_invite",
                to="groups.group",
            ),
        ),
    ]
